version: "3.3"

services:
  dashboard:
    image: ghcr.io/naiba/nezha-dashboard
    restart: always
    volumes:
      - ./data:/dashboard/data
    ports:
      - nz_site_port:80
      - nz_grpc_port:5555
